### ISSUE TITLE
Some planning / roadmapping 

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/campaign-access-eval#10]
I see current work as two streams 

## Create framework to comprehensively audit political candidate website w/ focus on Access
- Visual impairments (web accessibility standards more generally)
- Language diversity (fit with constituents) 
- Reading level 

Content 
- Length of description 
- number of pages per site 
- Policy substance (TBD)

## Create audit reports to potentially improve the accessibility of content 
- Ask candidates to fix Access issues and offer instruction (meaningfully) how to make these fixes 
- Monitor changes - to see what was fixed, when, and to what effect 

## Deliverables 
- Paper with quant descriptive analysis of 2021 municipal races, and potential for intervention 
- Dataset from 2021 races published for potential reuse 
- Framework for auditing - Ideally we want to be able to feed in candidate sites and generate a report of accessability and content
- Eventually make this public facing - Create a dashboard where someone can run an audit - compare candidates, etc. 

Next steps for 1
- Discuss on Wed PM

**Comment by JacksonMaxfield** [comment]
Building off of this, I have a list of features / stats I think should be easy to aggregate:

features normalized in two different ways:
1. number of pages for the website
2. unique words
3. total words
4. population of district area the person is running for
5. funding?

the features are:
1. numbers of errors
2. number of topics mentioned (can maybe train some model for this? -- this model could also be used for CDP later on too which is why I thought of this)
3. lexical complexity / reading level
4. change in number of errors pre and post email (they had very little time to update but may still have _something_)

and break all of these features down by:
1. race type (mayoral, council)
2. incumbent, ran previously but never in office, previously been in office but not incumbent, never ran
3. who won

---

I basically think there are less _features_ as there are normalization techniques but it is still quite a bit matrix of features.

**Comment by JacksonMaxfield** [comment]
On the above note:

the extra datasets needed to merge into our existing dataset would be:

* population stats (down to a district level in some cases(
* campaign funding
* history of candidate (bullet 2 of "break down features")
* and who won

**Comment by nniiicc** [comment]
It would be great to collect 1-4 programmatically - but we likely can't ... So can you describe (either with a dataframe or a doc) what we need and in what form (for example - how do we want to record who won)
